### ISSUE TITLE
Add mime type to ReadableProxy

### ISSUE THREAD

**Issue by a-stacey** [ivcap-works/legacy-ivcap-service-sdk-python#6]
It would be really helpful if ReadableProxy had the mime type (or file extension) available.

At the moment the implementation that I use makes use of ReadableProxy.as_local_file(). The issue here for me is that we let the underlying ML library read the image in from file and so the code that reads the image may vary. I've seen that the results of ReadableProxy.as_local_file() doesn't have an extension. This seems to work for the library that I'm currently testing against but in terms of making the implementation general and robust I'd really like to make sure the extension is present and correct (in case the library that is used in another implementation is not as forgiving here). I've inspected other fields to obtain this information, but the problem is that .name might be a URL and so again not contain a valid extension. Ideally we'd capture the mime type during download or preserve original extension from the file system when its a local file.

Failing this I'd probably need to use something like this: https://pypi.org/project/filetype/ to deal with this issue, but my preference would be to have this captured in the IVCAP process from the source.

**Comment by maxott** [comment]
Fixed in 6ebb3b3 (v0.4.0)

```
    for img_a in args.images:
        img_a.seek(0) # trigger download
        logger.info(f"mime-type: {img_a.mime_type}")
```
